version: "3"

services:
  client:
    image: xzsk2/gocqhttp-docker:dev
    volumes:
      - ./client:/data:delegated
      - /mnt/hdd-2/ergo_database:/mnt/hdd-2/ergo_database
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - bot


#  bot-monitor-web:
#    build: ./bot-monitor-web
#    ports:
#      - "9301:80"
#    environment:
#      - TZ=Asia/Shanghai
#    depends_on:
#      - bot

  bot:
    build:
      context: ./bot
      network: bridge
    volumes:
      - /mnt/hdd-2/ergo_database:/mnt/hdd-2/ergo_database
    expose:
      - "9080"
    environment:
      - TZ=Asia/Shanghai


#  glances:
#    build: ./dockers/glances
#    expose:
#      - "61208"
#    environment:
#      - TZ=Asia/Shanghai
#      - LANG=en_US.UTF-8
